version: "3"

services: 
    db_postgres:
        image: postgres:9.6
        volumes:
            - postgres_data:/var/lib/postgresql/postgres_data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: db_postgres

    django_app:
        build: .
        volumes:
            - static:/code/static
            - .:/code
        depends_on:
            - db_postgres

    nginx:
        image: nginx:1.13
        ports:
            - 5000:80
        volumes:
            - ./config/nginx/conf.d:/etc/nginx/conf.d
            - static:/code/static
        depends_on:
            - django_app

volumes:
    .:
    postgres_data:
    static:


