version: 2
jobs:
  deploy:
    machine: true
    working_directory: ~/code
    steps:
      - checkout
      - run:
          name: Deploy prod
          working_directory: ~/code
          command: ssh -o "StrictHostKeyChecking no" "ec2-user@ec2-18-236-139-222.us-west-2.compute.amazonaws.com -y" "cd ~/code;git stash;git checkout master; git pull origin master; sudo docker-compose -f docker-compose.yaml up --build -d; sudo docker system prune -f"
workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master